#!/usr/bin/env bash
set -euo pipefail

GROUP_BY_MAP=BOOST_FLAT

ENABLE_DELTA_INT=OFF
ENABLE_RLE_INT=ON
ENABLE_RLE_FLOAT=ON
ENABLE_RLE_STR=ON
ENABLE_DICT_INT=ON
ENABLE_DICT_FLOAT=ON
ENABLE_DICT_STR=ON
ENABLE_BITPACK_INT=ON
ENABLE_BITPACK_FLOAT=ON
ENABLE_BITPACK_STR=ON
ENABLE_LZ4=ON
ENABLE_ADAPTIVE=ON

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${ROOT_DIR}/build"

export CC="${CC:-clang-20}"
export CXX="${CXX:-clang++-20}"

cmake -S "${ROOT_DIR}" -B "${BUILD_DIR}" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTS=OFF \
    -DENABLE_RLE_INT="${ENABLE_RLE_INT}" \
    -DENABLE_RLE_FLOAT="${ENABLE_RLE_FLOAT}" \
    -DENABLE_RLE_STR="${ENABLE_RLE_STR}" \
    -DENABLE_DELTA_INT="${ENABLE_DELTA_INT}" \
    -DENABLE_DICT_INT="${ENABLE_DICT_INT}" \
    -DENABLE_DICT_FLOAT="${ENABLE_DICT_FLOAT}" \
    -DENABLE_DICT_STR="${ENABLE_DICT_STR}" \
    -DENABLE_LZ4="${ENABLE_LZ4}" \
    -DENABLE_BITPACK_INT="${ENABLE_BITPACK_INT}" \
    -DENABLE_BITPACK_FLOAT="${ENABLE_BITPACK_FLOAT}" \
    -DENABLE_BITPACK_STR="${ENABLE_BITPACK_STR}" \
    -DENABLE_ADAPTIVE="${ENABLE_ADAPTIVE}" \
    -DGROUP_BY_MAP="${GROUP_BY_MAP}"

cmake --build "${BUILD_DIR}" -j "$(nproc)"
